% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{ifxetex,ifluatex}
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={assignment 1},
  pdfauthor={pavan},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifluatex
  \usepackage{selnolig}  % disable illegal ligatures
\fi

\title{assignment 1}
\author{pavan}
\date{22/10/2021}

\begin{document}
\maketitle

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{rm}\NormalTok{(}\AttributeTok{list =} \FunctionTok{ls}\NormalTok{())}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(tidyverse)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## -- Attaching packages --------------------------------------- tidyverse 1.3.1 --
\end{verbatim}

\begin{verbatim}
## v ggplot2 3.3.5     v purrr   0.3.4
## v tibble  3.1.4     v dplyr   1.0.7
## v tidyr   1.1.3     v stringr 1.4.0
## v readr   2.0.2     v forcats 0.5.1
\end{verbatim}

\begin{verbatim}
## -- Conflicts ------------------------------------------ tidyverse_conflicts() --
## x dplyr::filter() masks stats::filter()
## x dplyr::lag()    masks stats::lag()
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{setwd}\NormalTok{(}\StringTok{"C:/Users/pavankumar pendela/Desktop/MSBA/Business analytics/assignment 1"}\NormalTok{)}
\NormalTok{Online\_Retail }\OtherTok{\textless{}{-}} \FunctionTok{read\_csv}\NormalTok{(}\StringTok{"Online\_Retail.csv"}\NormalTok{, }\AttributeTok{col\_types =} \FunctionTok{c}\NormalTok{(}\StringTok{"ccci?dcc"}\NormalTok{))}
\FunctionTok{head}\NormalTok{(Online\_Retail)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 6 x 8
##   InvoiceNo StockCode Description      Quantity InvoiceDate UnitPrice CustomerID
##   <chr>     <chr>     <chr>               <int> <chr>           <dbl> <chr>     
## 1 536365    85123A    WHITE HANGING H~        6 12/1/2010 ~      2.55 17850     
## 2 536365    71053     WHITE METAL LAN~        6 12/1/2010 ~      3.39 17850     
## 3 536365    84406B    CREAM CUPID HEA~        8 12/1/2010 ~      2.75 17850     
## 4 536365    84029G    KNITTED UNION F~        6 12/1/2010 ~      3.39 17850     
## 5 536365    84029E    RED WOOLLY HOTT~        6 12/1/2010 ~      3.39 17850     
## 6 536365    22752     SET 7 BABUSHKA ~        2 12/1/2010 ~      7.65 17850     
## # ... with 1 more variable: Country <chr>
\end{verbatim}

\hypertarget{show-the-breakdown-of-the-number-of-transactions-by-countries-i.e.-how-many-transactions-are-in-the-dataset-for-each-country-consider-all-records-including-cancelled-transactions.-show-this-in-total-number-and-also-in-percentage.-show-only-countries-accounting-for-more-than-1-of-the-total-transactions.}{%
\section{1. Show the breakdown of the number of transactions by
countries i.e.~how many transactions are in the dataset for each country
(consider all records including cancelled transactions). Show this in
total number and also in percentage. Show only countries accounting for
more than 1\% of the total
transactions.}\label{show-the-breakdown-of-the-number-of-transactions-by-countries-i.e.-how-many-transactions-are-in-the-dataset-for-each-country-consider-all-records-including-cancelled-transactions.-show-this-in-total-number-and-also-in-percentage.-show-only-countries-accounting-for-more-than-1-of-the-total-transactions.}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Online\_Retail }\SpecialCharTok{\%\textgreater{}\%}
\FunctionTok{group\_by}\NormalTok{(Country)  }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{tally}\NormalTok{(}\AttributeTok{sort =} \ConstantTok{TRUE}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{summarise}\NormalTok{(Country, }\AttributeTok{Counts =}\NormalTok{ n, }\AttributeTok{Percent =}\NormalTok{ n}\SpecialCharTok{/}\FunctionTok{sum}\NormalTok{(n)}\SpecialCharTok{*}\DecValTok{100}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{filter}\NormalTok{(Percent }\SpecialCharTok{\textgreater{}} \DecValTok{1}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 4 x 3
##   Country        Counts Percent
##   <chr>           <int>   <dbl>
## 1 United Kingdom 495478   91.4 
## 2 Germany          9495    1.75
## 3 France           8557    1.58
## 4 EIRE             8196    1.51
\end{verbatim}

UK, Germany, France, and EIRE account for more than 1\% of the total
transactions in this dataset.

\hypertarget{create-a-new-variable-transactionvalue-that-is-the-product-of-the-exising-quantity-and-unitprice-variables.-add-this-variable-to-the-dataframe.}{%
\section{2. Create a new variable `TransactionValue' that is the product
of the exising `Quantity' and `UnitPrice' variables. Add this variable
to the
dataframe.}\label{create-a-new-variable-transactionvalue-that-is-the-product-of-the-exising-quantity-and-unitprice-variables.-add-this-variable-to-the-dataframe.}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Online\_Retail }\OtherTok{\textless{}{-}} \FunctionTok{mutate}\NormalTok{(Online\_Retail, }\AttributeTok{TransactionValue =}\NormalTok{ Quantity }\SpecialCharTok{*}\NormalTok{ UnitPrice)}
\FunctionTok{head}\NormalTok{(Online\_Retail[, }\DecValTok{9}\NormalTok{])}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 6 x 1
##   TransactionValue
##              <dbl>
## 1             15.3
## 2             20.3
## 3             22  
## 4             20.3
## 5             20.3
## 6             15.3
\end{verbatim}

\hypertarget{using-the-newly-created-variable-transactionvalue-show-the-breakdown-of-transaction-values-by-countries-i.e.-how-much-money-in-total-has-been-spent-each-country.-show-this-in-total-sum-of-transaction-values.-show-only-countries-with-total-transaction-exceeding-130000-british-pound.}{%
\section{3. Using the newly created variable, TransactionValue, show the
breakdown of transaction values by countries i.e.~how much money in
total has been spent each country. Show this in total sum of transaction
values. Show only countries with total transaction exceeding 130,000
British
Pound.}\label{using-the-newly-created-variable-transactionvalue-show-the-breakdown-of-transaction-values-by-countries-i.e.-how-much-money-in-total-has-been-spent-each-country.-show-this-in-total-sum-of-transaction-values.-show-only-countries-with-total-transaction-exceeding-130000-british-pound.}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Online\_Retail }\SpecialCharTok{\%\textgreater{}\%}
\FunctionTok{group\_by}\NormalTok{(Country) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{summarise}\NormalTok{(}\AttributeTok{TransValueSum =} \FunctionTok{sum}\NormalTok{(TransactionValue)) }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{filter}\NormalTok{(TransValueSum }\SpecialCharTok{\textgreater{}} \DecValTok{130000}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{arrange}\NormalTok{(}\FunctionTok{desc}\NormalTok{(TransValueSum))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 6 x 2
##   Country        TransValueSum
##   <chr>                  <dbl>
## 1 United Kingdom      8187806.
## 2 Netherlands          284662.
## 3 EIRE                 263277.
## 4 Germany              221698.
## 5 France               197404.
## 6 Australia            137077.
\end{verbatim}

UK, Netherlands, EIRE, Germany, France, and Australia are the countries
where their sum is greater than 130,000 British Pound.

\hypertarget{we-are-dealing-with-the-invoicedate-variable.-the-variable-is-read-as-a-categorical-when-you-read-data-from-the-file.-now-we-need-to-explicitly-instruct-r-to-interpret-this-as-a-date-variable.-posixlt-and-posixct-are-two-powerful-object-classes-in-r-to-deal-with-date-and-time.-click-here-for-more-information.}{%
\section{4. we are dealing with the InvoiceDate variable. The variable
is read as a categorical when you read data from the file. Now we need
to explicitly instruct R to interpret this as a Date variable.
``POSIXlt'' and ``POSIXct'' are two powerful object classes in R to deal
with date and time. Click here for more
information.}\label{we-are-dealing-with-the-invoicedate-variable.-the-variable-is-read-as-a-categorical-when-you-read-data-from-the-file.-now-we-need-to-explicitly-instruct-r-to-interpret-this-as-a-date-variable.-posixlt-and-posixct-are-two-powerful-object-classes-in-r-to-deal-with-date-and-time.-click-here-for-more-information.}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Temp }\OtherTok{\textless{}{-}} \FunctionTok{strptime}\NormalTok{(Online\_Retail}\SpecialCharTok{$}\NormalTok{InvoiceDate,}\AttributeTok{format=}\StringTok{\textquotesingle{}\%m/\%d/\%Y \%H:\%M\textquotesingle{}}\NormalTok{,}\AttributeTok{tz=}\StringTok{\textquotesingle{}GMT\textquotesingle{}}\NormalTok{)}
\FunctionTok{head}\NormalTok{(Temp)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "2010-12-01 08:26:00 GMT" "2010-12-01 08:26:00 GMT"
## [3] "2010-12-01 08:26:00 GMT" "2010-12-01 08:26:00 GMT"
## [5] "2010-12-01 08:26:00 GMT" "2010-12-01 08:26:00 GMT"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{head}\NormalTok{(Online\_Retail)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 6 x 9
##   InvoiceNo StockCode Description      Quantity InvoiceDate UnitPrice CustomerID
##   <chr>     <chr>     <chr>               <int> <chr>           <dbl> <chr>     
## 1 536365    85123A    WHITE HANGING H~        6 12/1/2010 ~      2.55 17850     
## 2 536365    71053     WHITE METAL LAN~        6 12/1/2010 ~      3.39 17850     
## 3 536365    84406B    CREAM CUPID HEA~        8 12/1/2010 ~      2.75 17850     
## 4 536365    84029G    KNITTED UNION F~        6 12/1/2010 ~      3.39 17850     
## 5 536365    84029E    RED WOOLLY HOTT~        6 12/1/2010 ~      3.39 17850     
## 6 536365    22752     SET 7 BABUSHKA ~        2 12/1/2010 ~      7.65 17850     
## # ... with 2 more variables: Country <chr>, TransactionValue <dbl>
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Online\_Retail}\SpecialCharTok{$}\NormalTok{New\_Invoice\_Date }\OtherTok{\textless{}{-}} \FunctionTok{as.Date}\NormalTok{(Temp)}
\NormalTok{Online\_Retail}\SpecialCharTok{$}\NormalTok{Invoice\_Day\_Week }\OtherTok{\textless{}{-}} \FunctionTok{weekdays}\NormalTok{(Online\_Retail}\SpecialCharTok{$}\NormalTok{New\_Invoice\_Date)}
\NormalTok{Online\_Retail}\SpecialCharTok{$}\NormalTok{New\_Invoice\_Hour }\OtherTok{\textless{}{-}} \FunctionTok{as.numeric}\NormalTok{(}\FunctionTok{format}\NormalTok{(Temp, }\StringTok{"\%H"}\NormalTok{))}
\NormalTok{Online\_Retail}\SpecialCharTok{$}\NormalTok{New\_Invoice\_Month }\OtherTok{\textless{}{-}} \FunctionTok{as.numeric}\NormalTok{(}\FunctionTok{format}\NormalTok{(Temp, }\StringTok{"\%m"}\NormalTok{))}
\FunctionTok{head}\NormalTok{(Online\_Retail)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 6 x 13
##   InvoiceNo StockCode Description      Quantity InvoiceDate UnitPrice CustomerID
##   <chr>     <chr>     <chr>               <int> <chr>           <dbl> <chr>     
## 1 536365    85123A    WHITE HANGING H~        6 12/1/2010 ~      2.55 17850     
## 2 536365    71053     WHITE METAL LAN~        6 12/1/2010 ~      3.39 17850     
## 3 536365    84406B    CREAM CUPID HEA~        8 12/1/2010 ~      2.75 17850     
## 4 536365    84029G    KNITTED UNION F~        6 12/1/2010 ~      3.39 17850     
## 5 536365    84029E    RED WOOLLY HOTT~        6 12/1/2010 ~      3.39 17850     
## 6 536365    22752     SET 7 BABUSHKA ~        2 12/1/2010 ~      7.65 17850     
## # ... with 6 more variables: Country <chr>, TransactionValue <dbl>,
## #   New_Invoice_Date <date>, Invoice_Day_Week <chr>, New_Invoice_Hour <dbl>,
## #   New_Invoice_Month <dbl>
\end{verbatim}

\hypertarget{a-show-the-percentage-of-transactions-by-numbers-by-days-of-the-week}{%
\section{a) Show the percentage of transactions (by numbers) by days of
the
week}\label{a-show-the-percentage-of-transactions-by-numbers-by-days-of-the-week}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Online\_Retail }\SpecialCharTok{\%\textgreater{}\%}  
  \FunctionTok{group\_by}\NormalTok{(Invoice\_Day\_Week) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{tally}\NormalTok{(}\AttributeTok{sort =} \ConstantTok{TRUE}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{summarise}\NormalTok{(Invoice\_Day\_Week, }\AttributeTok{TransactionCounts =}\NormalTok{ n, }\AttributeTok{Percent =}\NormalTok{ n}\SpecialCharTok{/}\FunctionTok{sum}\NormalTok{(n)}\SpecialCharTok{*}\DecValTok{100}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{arrange}\NormalTok{(}\FunctionTok{desc}\NormalTok{(TransactionCounts))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 6 x 3
##   Invoice_Day_Week TransactionCounts Percent
##   <chr>                        <int>   <dbl>
## 1 Thursday                    103857    19.2
## 2 Tuesday                     101808    18.8
## 3 Monday                       95111    17.6
## 4 Wednesday                    94565    17.5
## 5 Friday                       82193    15.2
## 6 Sunday                       64375    11.9
\end{verbatim}

\hypertarget{b-show-the-percentage-of-transactions-by-transaction-volume-by-days-of-the-week}{%
\section{b) Show the percentage of transactions (by transaction volume)
by days of the
week}\label{b-show-the-percentage-of-transactions-by-transaction-volume-by-days-of-the-week}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Online\_Retail }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{group\_by}\NormalTok{(Invoice\_Day\_Week) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{summarise}\NormalTok{(}\AttributeTok{TransValueSum =} \FunctionTok{sum}\NormalTok{(TransactionValue)) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{TransValuePercent =}\NormalTok{ TransValueSum}\SpecialCharTok{/}\FunctionTok{sum}\NormalTok{(TransValueSum)) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{arrange}\NormalTok{(}\FunctionTok{desc}\NormalTok{(TransValueSum))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 6 x 3
##   Invoice_Day_Week TransValueSum TransValuePercent
##   <chr>                    <dbl>             <dbl>
## 1 Thursday              2112519             0.217 
## 2 Tuesday               1966183.            0.202 
## 3 Wednesday             1734147.            0.178 
## 4 Monday                1588609.            0.163 
## 5 Friday                1540611.            0.158 
## 6 Sunday                 805679.            0.0827
\end{verbatim}

\hypertarget{c-show-the-percentage-of-transactions-by-transaction-volume-by-month-of-the-year}{%
\section{c) Show the percentage of transactions (by transaction volume)
by month of the
year}\label{c-show-the-percentage-of-transactions-by-transaction-volume-by-month-of-the-year}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Online\_Retail }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{group\_by}\NormalTok{(New\_Invoice\_Month) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{summarise}\NormalTok{(}\AttributeTok{TransValueSum =} \FunctionTok{sum}\NormalTok{(TransactionValue)) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{TransValuePercent =}\NormalTok{ TransValueSum}\SpecialCharTok{/}\FunctionTok{sum}\NormalTok{(TransValueSum)) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{arrange}\NormalTok{(}\FunctionTok{desc}\NormalTok{(TransValuePercent))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 12 x 3
##    New_Invoice_Month TransValueSum TransValuePercent
##                <dbl>         <dbl>             <dbl>
##  1                11      1461756.            0.150 
##  2                12      1182625.            0.121 
##  3                10      1070705.            0.110 
##  4                 9      1019688.            0.105 
##  5                 5       723334.            0.0742
##  6                 6       691123.            0.0709
##  7                 3       683267.            0.0701
##  8                 8       682681.            0.0700
##  9                 7       681300.            0.0699
## 10                 1       560000.            0.0574
## 11                 2       498063.            0.0511
## 12                 4       493207.            0.0506
\end{verbatim}

\hypertarget{d-what-was-the-date-with-the-highest-number-of-transactions-from-australia}{%
\section{d) What was the date with the highest number of transactions
from
Australia}\label{d-what-was-the-date-with-the-highest-number-of-transactions-from-australia}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Online\_Retail }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{filter}\NormalTok{(Country }\SpecialCharTok{==} \StringTok{"Australia"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{group\_by}\NormalTok{(InvoiceDate) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{tally}\NormalTok{(}\AttributeTok{sort =} \ConstantTok{TRUE}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{filter}\NormalTok{(n }\SpecialCharTok{==} \FunctionTok{max}\NormalTok{(n))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 1 x 2
##   InvoiceDate         n
##   <chr>           <int>
## 1 6/15/2011 13:37   139
\end{verbatim}

\hypertarget{e-the-company-needs-to-shut-down-the-website-for-two-consecutive-hours-for-maintenance.-what-would-be-the-hour-of-the-day-to-start-this-so-that-the-distribution-is-at-minimum-for-the-customers-the-responsible-it-team-is-available-from-700-to-2000-every-day.}{%
\section{e) The company needs to shut down the website for two
consecutive hours for maintenance. What would be the hour of the day to
start this so that the distribution is at minimum for the customers? The
responsible IT team is available from 7:00 to 20:00 every
day.}\label{e-the-company-needs-to-shut-down-the-website-for-two-consecutive-hours-for-maintenance.-what-would-be-the-hour-of-the-day-to-start-this-so-that-the-distribution-is-at-minimum-for-the-customers-the-responsible-it-team-is-available-from-700-to-2000-every-day.}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Online\_Retail }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{group\_by}\NormalTok{(New\_Invoice\_Hour) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{tally}\NormalTok{(}\AttributeTok{sort =} \ConstantTok{TRUE}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{filter}\NormalTok{(New\_Invoice\_Hour}\SpecialCharTok{\textgreater{}=} \DecValTok{7} \SpecialCharTok{\&}\NormalTok{ New\_Invoice\_Hour}\SpecialCharTok{\textless{}=}\DecValTok{20}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{arrange}\NormalTok{(n) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{head}\NormalTok{(}\DecValTok{5}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 5 x 2
##   New_Invoice_Hour     n
##              <dbl> <int>
## 1                7   383
## 2               20   871
## 3               19  3705
## 4               18  7974
## 5                8  8909
\end{verbatim}

The answer is the 19th and 20th since they are the 2nd and 3rd lowest
values and then combined would be the lowest sum of two consecutive
hours.

\hypertarget{plot-the-histogram-of-transaction-values-from-germany.-use-the-hist-function-to-plot}{%
\section{5. Plot the histogram of transaction values from Germany. Use
the hist() function to
plot}\label{plot-the-histogram-of-transaction-values-from-germany.-use-the-hist-function-to-plot}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Online\_Retail }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{group\_by}\NormalTok{(Country) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{filter}\NormalTok{(Country }\SpecialCharTok{==} \StringTok{"Germany"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{group\_by}\NormalTok{(New\_Invoice\_Month) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{summarise}\NormalTok{(}\AttributeTok{TransValueSum =} \FunctionTok{sum}\NormalTok{(TransactionValue)) }\OtherTok{{-}\textgreater{}}\NormalTok{ Germany}
\FunctionTok{hist}\NormalTok{(Germany}\SpecialCharTok{$}\NormalTok{TransValueSum, }\AttributeTok{border =} \StringTok{"deepskyblue3"}\NormalTok{, }\AttributeTok{main =} \StringTok{"Germany Transaction Value"}\NormalTok{, }\AttributeTok{xlab =} \StringTok{"Transaction Value Sum per Month"}\NormalTok{, }\AttributeTok{ylab =} \StringTok{"Frequency"}\NormalTok{, }\AttributeTok{col =} \StringTok{"deepskyblue"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{assignment-1_files/figure-latex/unnamed-chunk-12-1.pdf}
\# 6. Which customer had the highest number of transactions? Which
customer is most valuable

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Online\_Retail }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{group\_by}\NormalTok{(CustomerID) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{tally}\NormalTok{(}\AttributeTok{sort =} \ConstantTok{TRUE}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{filter}\NormalTok{(}\SpecialCharTok{!}\FunctionTok{is.na}\NormalTok{(CustomerID)) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{filter}\NormalTok{(n}\SpecialCharTok{==}\FunctionTok{max}\NormalTok{(n))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 1 x 2
##   CustomerID     n
##   <chr>      <int>
## 1 17841       7983
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Online\_Retail }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{group\_by}\NormalTok{(CustomerID) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{summarise}\NormalTok{(}\AttributeTok{Transvaluesum =} \FunctionTok{sum}\NormalTok{(TransactionValue)) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{filter}\NormalTok{(}\SpecialCharTok{!}\FunctionTok{is.na}\NormalTok{(CustomerID)) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{filter}\NormalTok{(Transvaluesum }\SpecialCharTok{==} \FunctionTok{max}\NormalTok{(Transvaluesum))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 1 x 2
##   CustomerID Transvaluesum
##   <chr>              <dbl>
## 1 14646            279489.
\end{verbatim}

Customer 17841 has the most transactions of 7,983 and customer 14646 is
the most valuable spending 279,489 British Pound.

\hypertarget{calculate-the-percentage-of-missing-values-for-each-variable-in-the-dataset}{%
\section{7. Calculate the percentage of missing values for each variable
in the
dataset}\label{calculate-the-percentage-of-missing-values-for-each-variable-in-the-dataset}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{colMeans}\NormalTok{(}\FunctionTok{is.na}\NormalTok{(Online\_Retail))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##         InvoiceNo         StockCode       Description          Quantity 
##       0.000000000       0.000000000       0.002683107       0.000000000 
##       InvoiceDate         UnitPrice        CustomerID           Country 
##       0.000000000       0.000000000       0.249266943       0.000000000 
##  TransactionValue  New_Invoice_Date  Invoice_Day_Week  New_Invoice_Hour 
##       0.000000000       0.000000000       0.000000000       0.000000000 
## New_Invoice_Month 
##       0.000000000
\end{verbatim}

Only columns ``Description'' (.2\% missing values) and ``CustomerID''
(24.9\% missing values) have missing values.

\hypertarget{what-are-the-number-of-transactions-with-missing-customerid-records-by-countries}{%
\section{8. What are the number of transactions with missing CustomerID
records by
countries?}\label{what-are-the-number-of-transactions-with-missing-customerid-records-by-countries}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Online\_Retail }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{filter}\NormalTok{(}\FunctionTok{is.na}\NormalTok{(CustomerID)) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{group\_by}\NormalTok{(Country) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{summarise}\NormalTok{(CustomerID) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{tally}\NormalTok{(}\AttributeTok{sort =} \ConstantTok{TRUE}\NormalTok{) }\CommentTok{\# Total "NA" by country.}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `summarise()` has grouped output by 'Country'. You can override using the `.groups` argument.
\end{verbatim}

\begin{verbatim}
## # A tibble: 9 x 2
##   Country             n
##   <chr>           <int>
## 1 United Kingdom 133600
## 2 EIRE              711
## 3 Hong Kong         288
## 4 Unspecified       202
## 5 Switzerland       125
## 6 France             66
## 7 Israel             47
## 8 Portugal           39
## 9 Bahrain             2
\end{verbatim}

\hypertarget{on-average-how-often-the-costumers-comeback-to-the-website-for-their-next-shopping}{%
\section{9. On average, how often the costumers comeback to the website
for their next
shopping?}\label{on-average-how-often-the-costumers-comeback-to-the-website-for-their-next-shopping}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Online\_Retail }\SpecialCharTok{\%\textgreater{}\%} \CommentTok{\# Creating a variable for the number of days between visits.}
  \FunctionTok{select}\NormalTok{(CustomerID, New\_Invoice\_Date) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{group\_by}\NormalTok{(CustomerID) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{distinct}\NormalTok{(New\_Invoice\_Date) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{arrange}\NormalTok{(}\FunctionTok{desc}\NormalTok{(CustomerID)) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{DaysBetween =}\NormalTok{ New\_Invoice\_Date }\SpecialCharTok{{-}} \FunctionTok{lag}\NormalTok{(New\_Invoice\_Date))}\OtherTok{{-}\textgreater{}}\NormalTok{ CustDaysBtwVisit }\CommentTok{\#Combined DaysBetween per CustomerID.  }
 
\NormalTok{CustDaysBtwVisit }\SpecialCharTok{\%\textgreater{}\%} 
   \FunctionTok{filter}\NormalTok{(}\SpecialCharTok{!}\FunctionTok{is.na}\NormalTok{(DaysBetween)) }\OtherTok{{-}\textgreater{}}\NormalTok{ RetCustDaysBtwVisits }\CommentTok{\# Filtered "NA" from dataset.}
\FunctionTok{mean}\NormalTok{(RetCustDaysBtwVisits}\SpecialCharTok{$}\NormalTok{DaysBetween)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Time difference of 38.4875 days
\end{verbatim}

The customers who did return had an average of 38.5 days between visits.

\hypertarget{in-the-retail-sector-it-is-very-important-to-understand-the-return-rate-of-the-goods-purchased-by-customers.-in-this-example-we-can-define-this-quantity-simply-as-the-ratio-of-the-number-of-transactions-cancelled-regardless-of-the-transaction-value-over-the-total-number-of-transactions.-with-this-definition-what-is-the-return-rate-for-the-french-customers}{%
\section{10. In the retail sector, it is very important to understand
the return rate of the goods purchased by customers. In this example, we
can define this quantity, simply, as the ratio of the number of
transactions cancelled (regardless of the transaction value) over the
total number of transactions. With this definition, what is the return
rate for the French
customers?}\label{in-the-retail-sector-it-is-very-important-to-understand-the-return-rate-of-the-goods-purchased-by-customers.-in-this-example-we-can-define-this-quantity-simply-as-the-ratio-of-the-number-of-transactions-cancelled-regardless-of-the-transaction-value-over-the-total-number-of-transactions.-with-this-definition-what-is-the-return-rate-for-the-french-customers}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Online\_Retail }\SpecialCharTok{\%\textgreater{}\%} \CommentTok{\# Found the returns from France.}
  \FunctionTok{group\_by}\NormalTok{(Country) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{filter}\NormalTok{(Country }\SpecialCharTok{==} \StringTok{"France"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{select}\NormalTok{(Country, Quantity) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{filter}\NormalTok{(Quantity }\SpecialCharTok{\textless{}} \DecValTok{0}\NormalTok{) }\OtherTok{{-}\textgreater{}}\NormalTok{ FrenchReturns}
\NormalTok{  Online\_Retail }\SpecialCharTok{\%\textgreater{}\%}  \CommentTok{\# Found the purchases from France.}
  \FunctionTok{group\_by}\NormalTok{(Country) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{filter}\NormalTok{(Country }\SpecialCharTok{==} \StringTok{"France"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{select}\NormalTok{(Quantity, Country) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{filter}\NormalTok{(Quantity }\SpecialCharTok{\textgreater{}} \DecValTok{0}\NormalTok{) }\OtherTok{{-}\textgreater{}}\NormalTok{ FrenchPurchases}
\NormalTok{FRReturns }\OtherTok{\textless{}{-}} \FunctionTok{sum}\NormalTok{(FrenchReturns}\SpecialCharTok{$}\NormalTok{Quantity) }\CommentTok{\# calculated the quantity of returns from France.}
\NormalTok{FRTransactions }\OtherTok{\textless{}{-}} \FunctionTok{sum}\NormalTok{(FrenchPurchases}\SpecialCharTok{$}\NormalTok{Quantity) }\CommentTok{\# calculated the quanity of purchased from France.}
\NormalTok{FRReturns}\SpecialCharTok{/}\NormalTok{FRTransactions }\SpecialCharTok{*}\DecValTok{100} \CommentTok{\# Using the above two numbers, I then calculated the return rate.}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] -1.448655
\end{verbatim}

France has a 1.45\% return rate.

\hypertarget{what-is-the-product-that-has-generated-the-highest-revenue-for-the-retailer}{%
\section{11. What is the product that has generated the highest revenue
for the
retailer?}\label{what-is-the-product-that-has-generated-the-highest-revenue-for-the-retailer}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Online\_Retail }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{group\_by}\NormalTok{(StockCode) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{summarise}\NormalTok{(}\AttributeTok{TransactionValueTot =} \FunctionTok{sum}\NormalTok{(TransactionValue)) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{arrange}\NormalTok{(}\FunctionTok{desc}\NormalTok{(TransactionValueTot)) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{filter}\NormalTok{(StockCode }\SpecialCharTok{!=} \StringTok{"DOT"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}  \CommentTok{\# Looks like this is postage for delivering products.}
  \FunctionTok{filter}\NormalTok{(TransactionValueTot }\SpecialCharTok{==} \FunctionTok{max}\NormalTok{(TransactionValueTot))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 1 x 2
##   StockCode TransactionValueTot
##   <chr>                   <dbl>
## 1 22423                 164762.
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Online\_Retail }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{group\_by}\NormalTok{(StockCode) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{filter}\NormalTok{(StockCode }\SpecialCharTok{==} \StringTok{"22423"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{select}\NormalTok{(StockCode, Description) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{distinct}\NormalTok{(StockCode, Description) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{filter}\NormalTok{(Description }\SpecialCharTok{==} \StringTok{"REGENCY CAKESTAND 3 TIER"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 1 x 2
## # Groups:   StockCode [1]
##   StockCode Description             
##   <chr>     <chr>                   
## 1 22423     REGENCY CAKESTAND 3 TIER
\end{verbatim}

Regency 3 tiered cakestand had the highest revenue.

\hypertarget{how-many-unique-customers-are-represented-in-the-dataset}{%
\section{12. How many unique customers are represented in the
dataset?}\label{how-many-unique-customers-are-represented-in-the-dataset}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Online\_Retail }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{group\_by}\NormalTok{(CustomerID) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{distinct}\NormalTok{(CustomerID) }\OtherTok{{-}\textgreater{}}\NormalTok{ UniqueCustomers}
  \FunctionTok{length}\NormalTok{(UniqueCustomers}\SpecialCharTok{$}\NormalTok{CustomerID)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 4373
\end{verbatim}

There are 4373 unique customers in this dataset.

\end{document}
